name: Deploy to Public Repository

on:
  workflow_run:
    workflows: ["Validate JSON Schema"]  # Name of the validation workflow
    types:
      - completed

jobs:
  deploy:
    # Run only if the validation workflow was successful and it is a push to the main branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the app-config repository
      - name: Checkout app-config
        uses: actions/checkout@v4

      # Copy app-config.json to the public repo
      - name: Copy app-config.json
        env:
          APP_CONFIG_TOKEN: ${{ secrets.APP_CONFIG_TOKEN }}
        run: |
          # Clone the public repository
          git clone https://github.com/owahlen/app-config-public.git
          
          # Copy the file to the public repo directory
          mkdir -p app-config-public/docs
          cp app-config.json app-config-public/docs/

          # Change to the public repo directory
          cd app-config-public
          
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Commit and push the changes
          git add docs/app-config.json
          git commit -m "Update app-config.json"
          git push https://owahlen:${APP_CONFIG_TOKEN}@github.com/owahlen/app-config-public.git HEAD:main
